# Generated by Django 5.1.4 on 2024-12-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='was_selected',
            field=models.BooleanField(default=False),
        ),
    ]
