# Generated by Django 5.1.4 on 2024-12-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_recipe_was_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipe_api_id',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
