# Generated by Django 5.1.4 on 2024-12-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_ingredient_recipe_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe_id',
        ),
    ]
