# Generated by Django 5.1.4 on 2024-12-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_remove_ingredient_recipe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='recipe_id',
        ),
        migrations.AddField(
            model_name='procedure',
            name='recipe_api_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
