# Generated by Django 5.1.4 on 2024-12-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_remove_procedure_recipe_id_procedure_recipe_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='info',
            field=models.CharField(default='Error', max_length=50),
            preserve_default=False,
        ),
    ]
