# Generated by Django 5.1.4 on 2024-12-14 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_ingredient_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=150)),
                ('ready_in_minutes', models.IntegerField(blank=True, null=True)),
                ('servings', models.IntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('weight_watchers_points', models.IntegerField(blank=True, null=True)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegen', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('dairy_free', models.BooleanField(default=False)),
                ('low_fodmap', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Recipe',
            new_name='UserRecipe',
        ),
    ]
