# Generated by Django 5.1.4 on 2024-12-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0007_recipeinformation_rename_recipe_userrecipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeinformation',
            old_name='api_id',
            new_name='recipe_api_id',
        ),
        migrations.AddField(
            model_name='recipeinformation',
            name='source_name',
            field=models.CharField(default='old_data', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeinformation',
            name='source_url',
            field=models.CharField(default='old__data', max_length=150),
            preserve_default=False,
        ),
    ]
