# Generated by Django 5.1.4 on 2024-12-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0009_recipeinformation_cook_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinformation',
            name='source_url',
            field=models.URLField(max_length=150),
        ),
    ]
