# Generated by Django 5.1.4 on 2024-12-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0010_alter_recipeinformation_source_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeinformation',
            old_name='vegen',
            new_name='vegan',
        ),
    ]
