# Generated by Django 5.1.4 on 2024-12-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0011_rename_vegen_recipeinformation_vegan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecipe',
            name='date_searched',
            field=models.DateField(auto_now=True),
        ),
    ]
