# Generated by Django 5.1.4 on 2024-12-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0012_userrecipe_date_searched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='date_searched',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
