# Generated by Django 5.1.4 on 2024-12-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0013_alter_userrecipe_date_searched'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecipe',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
